export const FETCH_PROFILEUPDATE_REQUEST = 'FETCH_PROFILEUPDATE_REQUEST';
export const FETCH_PROFILEUPDATE_SUCCESS = 'FETCH_PROFILEUPDATE_SUCCESS';
export const FETCH_PROFILEUPDATE_FAILURE = 'FETCH_PROFILEUPDATE_FAILURE';
