export const FETCH_POSTDELETE_REQUEST = 'FETCH_POSTDELETE_REQUEST';
export const FETCH_POSTDELETE_SUCCESS = 'FETCH_POSTDELETE_SUCCESS';
export const FETCH_POSTDELETE_FAILURE = 'FETCH_POSTDELETE_FAILURE';
